[package]
name = "file_searcher"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fsearch"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
regex = "1.9"
colored = "2.0"
indicatif = "0.17"
rayon = "1.7"
memmap2 = "0.5"


